# Generated by Django 2.2 on 2022-08-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
