# Generated by Django 2.2 on 2022-08-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20220806_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
    ]
