# Generated by Django 2.2 on 2022-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20220821_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AdvertisementHeading',
            },
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvertisementStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvertisementType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterModelTable(
            name='advertisements',
            table='Advertisement',
        ),
        migrations.AlterModelTable(
            name='advertisementstatus',
            table='AdvertisementStatus',
        ),
        migrations.AlterModelTable(
            name='advertisementtype',
            table='AdvertisementType',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('advertisements', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.Advertisement', verbose_name='Автор')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.AddField(
            model_name='advertisements',
            name='heading',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.AdvertisementHeading', verbose_name='Категория'),
        ),
    ]
